{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cs.testplugin",
    "module": "Plugin",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "Plugin-0.0.1.jar",
          "url": "Plugin-0.0.1.jar",
          "size": 21688,
          "sha512": "bfaff2a9c107c9e666346f884f009da054a4de057f8609acb3bcc2f637b3d66ca2c2619900c5b7a53cd659646f189674030044aae09b14c20b016377e1c82cee",
          "sha256": "dccd8c038e98c2f753caca29a783ce2fcca9fafb05e2f034ab8d3f991f6c82fc",
          "sha1": "15f0841a4af78874f67907ead134813f953b416d",
          "md5": "f19b5c6774a4ca5f4e8d3a52f684a8db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "Plugin-0.0.1.jar",
          "url": "Plugin-0.0.1.jar",
          "size": 21688,
          "sha512": "bfaff2a9c107c9e666346f884f009da054a4de057f8609acb3bcc2f637b3d66ca2c2619900c5b7a53cd659646f189674030044aae09b14c20b016377e1c82cee",
          "sha256": "dccd8c038e98c2f753caca29a783ce2fcca9fafb05e2f034ab8d3f991f6c82fc",
          "sha1": "15f0841a4af78874f67907ead134813f953b416d",
          "md5": "f19b5c6774a4ca5f4e8d3a52f684a8db"
        }
      ]
    }
  ]
}
